name=IF97duino
version=v1.4_release
author=Rowan Zhang <rowanzhang123@gmail.com>
maintainer=Rowan Zhang <rowanzhang123@gmail.com>
sentence=CoolProp IF97 backend ported to the Arduino ecosystem as a meme
paragraph=Uses the same function calls as the CoolProp library, original (unmodified) library included as a zip file
category=Data Processing
url=https://github.com/rowanzhang123/IF97duino
architectures=stm32
includes=IF97.h